# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModelTrainer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModelTrainerUI(object):
    def setupUi(self, ModelTrainerUI):
        ModelTrainerUI.setObjectName("ModelTrainerUI")
        ModelTrainerUI.resize(815, 607)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModelTrainerUI)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ModelTrainerUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.location_Text = QtWidgets.QLineEdit(ModelTrainerUI)
        self.location_Text.setEnabled(False)
        self.location_Text.setReadOnly(True)
        self.location_Text.setObjectName("location_Text")
        self.horizontalLayout.addWidget(self.location_Text)
        self.choose_Button = QtWidgets.QPushButton(ModelTrainerUI)
        self.choose_Button.setObjectName("choose_Button")
        self.horizontalLayout.addWidget(self.choose_Button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ModelTrainerUI)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.model_location_Text = QtWidgets.QLineEdit(ModelTrainerUI)
        self.model_location_Text.setEnabled(False)
        self.model_location_Text.setReadOnly(True)
        self.model_location_Text.setObjectName("model_location_Text")
        self.horizontalLayout_2.addWidget(self.model_location_Text)
        self.save_choose_Button = QtWidgets.QPushButton(ModelTrainerUI)
        self.save_choose_Button.setEnabled(False)
        self.save_choose_Button.setObjectName("save_choose_Button")
        self.horizontalLayout_2.addWidget(self.save_choose_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.progressBar = QtWidgets.QProgressBar(ModelTrainerUI)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.progress_Label = QtWidgets.QLabel(ModelTrainerUI)
        self.progress_Label.setText("")
        self.progress_Label.setObjectName("progress_Label")
        self.verticalLayout.addWidget(self.progress_Label)
        self.fit_output_box = QtWidgets.QGroupBox(ModelTrainerUI)
        self.fit_output_box.setMinimumSize(QtCore.QSize(800, 400))
        self.fit_output_box.setObjectName("fit_output_box")
        self.verticalLayout.addWidget(self.fit_output_box)
        spacerItem = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.fit_Button = QtWidgets.QPushButton(ModelTrainerUI)
        self.fit_Button.setEnabled(False)
        self.fit_Button.setObjectName("fit_Button")
        self.verticalLayout.addWidget(self.fit_Button)

        self.retranslateUi(ModelTrainerUI)
        QtCore.QMetaObject.connectSlotsByName(ModelTrainerUI)

    def retranslateUi(self, ModelTrainerUI):
        _translate = QtCore.QCoreApplication.translate
        ModelTrainerUI.setWindowTitle(_translate("ModelTrainerUI", "Form"))
        self.label.setText(_translate("ModelTrainerUI", "Data location"))
        self.choose_Button.setText(_translate("ModelTrainerUI", "Choose..."))
        self.label_2.setText(_translate("ModelTrainerUI", "Output model:"))
        self.save_choose_Button.setText(_translate("ModelTrainerUI", "Choose..."))
        self.fit_output_box.setTitle(_translate("ModelTrainerUI", "Fitting output"))
        self.fit_Button.setText(_translate("ModelTrainerUI", "Fit model"))
